### ISSUE TITLE
First release checklist

### ISSUE THREAD

**Issue by ef4** [ef4/tracked-params#1]
- [ ] offer a test-support API that can set initial params and assert about current params (all talking about the strings in the URL, not the values in the models)
 - [ ] maybe make the param order stable. Right now the URL bar can visually flicker when the order changes as params go from unclaimed to claimed. I don't think this actually breaks anything but it annoys me.'
 - [ ] backfill some test coverage
 - [x] write a readme
    - [x] the core decorator `trackedParam`
    - [x] the included other types: bool and number
    - [x] how to use `createTrackedParam` to customize and create more types
    - [x] installation with location setup
    - [x] using with other custom locations
    - [x] how we fall back to a normal tracked property when no routing is around us, and the test facilities for controlling this
 - [ ] allow configurable interop with classic query params: explicit opt-in and/or opt-out lists of params so that we can decide which ones to handle in this addon and which ones to let the classic router handle.
